### ISSUE TITLE
ondevice pipe doesn't exit when it loses the connection

### ISSUE THREAD

**Issue by mreithub** [ondevice/ondevice#15]
To reproduce, simply connect to a device (`ondevice ssh user@myDevice`) and put the client PC into sleep mode for a few minutes. The device and the API server will close the connection. The client will notice that too but the `error` doesn't seem to get propagated properly.

Here's an example (I manually killed `ondevice :pipe` with `SIGABRT` to obtain a stack trace. The last line is `ssh` noticing that the connection's been lost and quitting):

```
2017/03/16 17:06:28 Error: tunnel timeout, closing connection...

# stuck here, then I kill it with `kill -ABRT` $pid:

SIGABRT: abort
PC=0x76bf8 m=0

goroutine 1 [syscall, 5 minutes]:
syscall.Syscall(0x3, 0x0, 0xc42032c000, 0x1fa4, 0x2, 0x4f3d60, 0xc420074940)
        /usr/local/Cellar/go/1.7.4_2/libexec/src/syscall/asm_darwin_amd64.s:16 +0x5 fp=0xc4201199d8 sp=0xc4201199d0
syscall.read(0x0, 0xc42032c000, 0x1fa4, 0x1fa4, 0x4f3d60, 0xc420074940, 0x0)
        /usr/local/Cellar/go/1.7.4_2/libexec/src/syscall/zsyscall_darwin_amd64.go:973 +0x55 fp=0xc420119a30 sp=0xc4201199d8
syscall.Read(0x0, 0xc42032c000, 0x1fa4, 0x1fa4, 0xc420396050, 0x8, 0x5)
        /usr/local/Cellar/go/1.7.4_2/libexec/src/syscall/syscall_unix.go:161 +0x49 fp=0xc420119a78 sp=0xc420119a30
os.(*File).read(0xc420082000, 0xc42032c000, 0x1fa4, 0x1fa4, 0x30, 0x4f3d60, 0xc420074940)
        /usr/local/Cellar/go/1.7.4_2/libexec/src/os/file_unix.go:228 +0x6a fp=0xc420119ac0 sp=0xc420119a78
os.(*File).Read(0xc420082000, 0xc42032c000, 0x1fa4, 0x1fa4, 0x29, 0x30, 0x5)
        /usr/local/Cellar/go/1.7.4_2/libexec/src/os/file.go:101 +0x59 fp=0xc420119b28 sp=0xc420119ac0
bufio.(*Reader).Read(0xc4200a43c0, 0xc42032c000, 0x1fa4, 0x1fa4, 0x24, 0x0, 0x0)
        /usr/local/Cellar/go/1.7.4_2/libexec/src/bufio/bufio.go:199 +0xc7 fp=0xc420119b78 sp=0xc420119b28
github.com/ondevice/ondevice/command.(*PipeCmd).run(0xc4200ee640, 0xc42007c120, 0x2, 0x2, 0xc4200b6d38)
        /Users/manuel/git/ondevice/ondevice-debian/macos/src/github.com/ondevice/ondevice/command/pipe.go:81 +0x4ca fp=0xc420119e50 sp=0xc420119b78
github.com/ondevice/ondevice/command.Run(0x7fff5fbffc59, 0x5, 0xc42007c120, 0x2, 0x2, 0x4f90e0)
        /Users/manuel/git/ondevice/ondevice-debian/macos/src/github.com/ondevice/ondevice/command/command.go:49 +0xb3 fp=0xc420119ed8 sp=0xc420119e50
main.main()
        /Users/manuel/git/ondevice/ondevice-debian/macos/src/github.com/ondevice/ondevice/ondevice.go:17 +0x92 fp=0xc420119f38 sp=0xc420119ed8
runtime.main()
        /usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/proc.go:183 +0x1f4 fp=0xc420119f90 sp=0xc420119f38
runtime.goexit()
        /usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420119f98 sp=0xc420119f90

goroutine 17 [syscall, 1587 minutes, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/asm_amd64.s:2086 +0x1

rax    0x2000003
rbx    0xc42001e00c
rcx    0xc4201199d0
rdx    0x1fa4
rdi    0x0
rsi    0xc42032c000
rbp    0xc420119a20
rsp    0xc4201199d0
r8     0x0
r9     0x0
r10    0x0
r11    0x206
r12    0x30
r13    0x90
r14    0x1c
r15    0x3
rip    0x76bf8
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
packet_write_wait: Connection to UNKNOWN port 65535: Broken pipe
```

**Comment by mreithub** [comment]
By the looks of it the issue is that `ondevice pipe`'s `run()` method blocks in `p.reader.Read()`.  
The issue can be resolved by adding a `CloseListener` and calling `os.Stdin.Close()`
